In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

base_url = "https://github.com/WincAcademy/practice_data/raw/main/data/geo/"
provinces_url = f"{base_url}provinces.csv"

province_names = [
  "drenthe",
  "flevoland",
  "friesland",
  "gelderland",
  "groningen",
  "limburg",
  "noord-brabant",
  "noord-holland",
  "overijssel",
  "utrecht",
  "zeeland",
  "zuid-holland"
]

municipalities_urls = [
  f"{base_url}municipalities/{prov_name}.csv" for prov_name in province_names
]

pr_df = pd.read_csv(provinces_url)

mun_df = pd.concat([pd.read_csv(url) for url in municipalities_urls])
display(mun_df)

pr_df2 = pr_df.drop(columns=["capital", "commissioner","anthem", "ISO 3166", "website", "num_municipalities"]

pr_df3 = pr_df2.rename(columns={
  "surface_sq_km": "surface"
})

pr_df4 = pr_df3.set_index("province")

pr_df4['density'] = pr_df4['inhabitants'] / pr_df4['surface']

pr_df5 = pr_df4.drop(columns=["inhabitants", "surface"])
pr_df5.columns = ["province_density"]
display(pr_df5)

mun_df2 = mun_df.drop(columns=["CBS code"])

mun_df4 = mun_df3.rename(columns={
  "Province": "province",
  "Inhabitants":"inhabitants",
  "Surface Area in sq km":"surface"
})

mun_df4['density'] = mun_df4['inhabitants'] / mun_df4['surface']

mun_df5 = mun_df4.drop(columns=["inhabitants", "surface"])
mun_df5.columns = ["province", "mun_density"]

mun_df5['municipality'] = mun_df5.index
display(mun_df5)

df = pd.merge(mun_df5, pr_df5, on="province")

df = df.set_index("municipality")

df['relative_density'] = df['mun_density'] / df['province_density']

df = df.sort_values(by="relative_density", ascending=False)
df_top = df.head(10)
display(df_top)

fig, ax = plt.subplots()

municipalities = df_top.index
relative_density = df_top.loc[:,"relative_density"]
ax.barh(municipalities, relative_density)
ax.invert_yaxis() 
plt.xlabel("Relative inhabitants density")
plt.ylabel("Municipality")
ax.grid(True, axis="x") 
plt.title("Busy municipalities in a quiet province")

fig.set_size_inches(20,10) 

plt.show()

     Municipality  CBS code      Province  Inhabitants  Surface Area in sq km
0     Aa en Hunze    1680.0       Drenthe      25445.0                 276.09
1           Assen     106.0       Drenthe      68599.0                  81.89
2   Borger-Odoorn    1681.0       Drenthe      25559.0                 274.53
3       Coevorden     109.0       Drenthe      35297.0                 296.07
4       De Wolden    1690.0       Drenthe      24330.0                 224.55
..            ...       ...           ...          ...                    ...
47     Westvoorne     614.0  Zuid-Holland      14731.0                  53.18
48     Zoetermeer     637.0  Zuid-Holland     125285.0                  34.45
49    Zoeterwoude     638.0  Zuid-Holland       8605.0                  21.19
50       Zuidplas    1892.0  Zuid-Holland      43885.0                  58.02
51    Zwijndrecht     642.0  Zuid-Holland      44737.0                  20.30

[352 rows x 5 columns]

               province_density
province
Groningen            252.202325
Friesland            194.889655
Drenthe              187.569149
Overijssel           350.227779
Flevoland            299.802268
Gelderland           420.300625
Utrecht              912.346128
Noord-Holland       1080.903529
Zuid-Holland        1373.591111
Zeeland              215.200898
Noord-Brabant        522.518858
Limburg              520.596925

NameError: ignored